### ISSUE TITLE
while pulling sub module, gives permission denied error.

### ISSUE THREAD

**Issue by hafizali05** [npvn/meteor-url-shortener#4]
I am getting the below given error when I try to install submodule.

sam@Sam-l554d:~/meteor-url-shortener$ git submodule update --init --recursive
Cloning into 'client/lib/meteor-material-design'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@bitbucket.org:npvn/meteor-material-design.git' into submodule path 'client/lib/meteor-material-design' failed

**Comment by npvn** [comment]
Hey @hafizali05, sorry for the late reply. I hosted the `meteor-material-design` submodule on bitbucket and used a `git://` URL, so you were not able to clone it because you didn't have a public key registered with bitbucket.

I just updated the submodule URL to `https`. Now you can clone without the need of registering your key:

`git clone --recursive https://github.com/npvn/meteor-url-shortener.git`
